// Textos legales compartidos entre el formulario de inscripción (Registro.jsx)
// y el onboarding de beneficiarios históricos (BeneficiarioOnboarding.jsx).

export const TERMS_AND_CONDITIONS_TEXT = [
  'ACEPTACIÓN DE TÉRMINOS Y CONDICIONES FONDO EDUCATIVO PARA EL APOYO DE LA EDUCACIÓN SUPERIOR (FOCADES).',
  'Yo, como aspirante al programa FOCADES, declaro de manera libre y voluntaria que he leído, comprendido y acepto en su totalidad los siguientes términos y condiciones, los cuales se basan en el Acuerdo N° 014 del 04 de septiembre de 2020 expedido por el Concejo Municipal de Montelíbano.',
  'CLÁUSULA PRIMERA: OBJETO DEL APOYO. Entiendo que el apoyo otorgado por FOCADES es un CRÉDITO EDUCATIVO CONDONABLE, blando y sin intereses, destinado a financiar estudios de educación técnica profesional, tecnológica o de pregrado. La exoneración del pago de hasta el 100% de la deuda está sujeta al cumplimiento estricto de las condiciones aquí descritas (Acuerdo N° 014 de 2020, Artículos Tercero y Cuarto).',
  'CLÁUSULA SEGUNDA: REQUISITOS DE ELEGIBILIDAD. Manifiesto que cumplo con los requisitos de la modalidad a la que aplico (Apoyo al Mérito Educativo o Apoyo a Sueños Educativos), los cuales incluyen, entre otros: ser egresado de una institución educativa oficial de Montelíbano, tener mi núcleo familiar domiciliado en el municipio, y no ser beneficiario de otra beca o estímulo de valor superior al crédito de FOCADES (Acuerdo N° 014 de 2020, Artículo Sexto).',
  'CLÁUSULA TERCERA: CONDICIÓN FUNDAMENTAL PARA LA CONDONACIÓN. Soy consciente de que la condición principal para que el crédito sea condonado es que, una vez finalizado cada semestre académico financiado, debo obtener un promedio de notas igual o superior a 3.2. El incumplimiento de esta condición me hará deudor del monto desembolsado en dicho semestre (Acuerdo N° 014 de 2020, Artículo Quinto y Noveno).',
  'CLÁUSULA CUARTA: CAUSALES DE PÉRDIDA DEL BENEFICIO. Acepto que el derecho al apoyo de FOCADES se pierde de forma inmediata si incurro en cualquiera de las siguientes causales: obtener un promedio académico inferior a 3.2 en el semestre financiado; haber perdido el semestre académico en el cual se me entregó el crédito; retirarme del programa académico por un semestre sin justa causa y sin notificar oportunamente al Comité de FOCADES; que mi matrícula sea cancelada por la Institución de Educación Superior por incumplimiento del reglamento interno; incurrir en cualquier acción delictiva o fraudulenta para favorecerme de los beneficios del programa (Acuerdo N° 014 de 2020, Artículo Noveno).',
  'CLÁUSULA QUINTA: VERACIDAD Y AUTENTICIDAD. Doy fe de que toda la información suministrada en el formulario de inscripción y los documentos adjuntos son veraces, exactos y auténticos. Autorizo al Comité Administrador del FOCADES a realizar las verificaciones pertinentes para comprobar la veracidad de los datos y documentos presentados (Acuerdo N° 014 de 2020, Artículo Décimo Noveno).',
  'CLÁUSULA SEXTA: COMPROMISO. Me comprometo a cumplir con todas las normativas, reglamentos y procesos establecidos por el programa FOCADES, incluyendo el proceso de actualización semestral de documentos para la renovación del beneficio, en caso de ser seleccionado.',
];

export const DATA_POLICY_TEXT = [
  'AUTORIZACIÓN PARA EL TRATAMIENTO DE DATOS PERSONALES PROGRAMA FOCADES - MUNICIPIO DE MONTELÍBANO.',
  'Yo, como aspirante, de manera libre, previa, expresa e informada, autorizo al Municipio de Montelíbano y al Comité Administrador del Fondo Educativo para el Apoyo de la Educación Superior (FOCADES), en adelante EL PROGRAMA, para realizar el tratamiento de mis datos personales, en cumplimiento de la Ley 1581 de 2012 y demás normas concordantes.',
  'CLÁUSULA PRIMERA: DATOS A TRATAR. La autorización se otorga para el tratamiento de la siguiente información: Datos de Identificación (nombres, apellidos, tipo y número de documento, fecha de nacimiento, género, correo electrónico, celular, dirección), Datos Socioeconómicos (núcleo familiar, ingresos, SISBEN, subsidios, zona y enfoque diferencial) y Datos Académicos (institución de egreso, Saber 11, institución de educación superior y programa).',
  'CLÁUSULA SEGUNDA: FINALIDADES DEL TRATAMIENTO. Autorizo que mis datos personales sean recolectados, almacenados, usados, circulados, actualizados y procesados para: verificar identidad y elegibilidad; evaluar solicitud y asignar puntaje de selección; comprobar veracidad de información y documentos; contactarme sobre el estado de postulación; gestionar vinculación, desembolsos y seguimiento académico en caso de selección; y generar informes estadísticos y reportes anónimos del impacto del programa.',
  'CLÁUSULA TERCERA: DERECHOS DEL TITULAR. Declaro que he sido informado(a) de mis derechos como titular de los datos: conocer, actualizar y rectificar mi información; solicitar prueba de la autorización otorgada; ser informado sobre el uso de mis datos; presentar quejas ante la autoridad competente; y revocar la autorización o solicitar supresión del dato cuando no se respeten los principios, derechos y garantías constitucionales y legales.',
  'Por lo anterior, otorgo mi consentimiento explícito a EL PROGRAMA para el tratamiento de mis datos personales de acuerdo con las finalidades aquí descritas.',
];
